# Generated by Django 4.0.1 on 2022-01-28 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('religiao', models.CharField(max_length=150, verbose_name='religião')),
                ('local', models.CharField(max_length=150, verbose_name='Local')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Culto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_culto', models.CharField(max_length=150)),
                ('descricao', models.TextField(max_length=150, verbose_name='descrição')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='data/hora')),
                ('igreja', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.igreja')),
            ],
        ),
    ]
