# Generated by Django 4.0.1 on 2022-04-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culto',
            options={'ordering': ['data']},
        ),
    ]
